name: CI

on:
  push:
    branches:
      - main # Ändra till din huvudgren om det är annorlunda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout koden
      uses: actions/checkout@v2

    - name: Installera beroenden och köra tester
      run: |
        npm install
        npm test -- --coverage

    - name: Samla in testtäckning
      uses: actions/upload-artifact@v2
      with:
        name: coverage
        path: coverage
