name: CI/CD Pipeline

on:
  pull_request:
    branches:
      - main # Ändra till din huvudgren om det är annorlunda

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout koden
      uses: actions/checkout@v2

    - name: Installera beroenden
      run: npm install

    - name: Kör tester
      run: npm test

    - name: Kontrollera testresultat
      run: |
        if [ ${{ job.status }} != 'success' ]; then
          echo "Testerna misslyckades, förhindrar merge."
          exit 1
        fi
